
env:
  browser: true
  es6: true
  jest: true
  jest/globals: true
  node: true
extends:
  - airbnb
  - airbnb-typescript
  - plugin:prettier/recommended
  - prettier/react
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  expect: true
  it: true
  describe: true
  jest: true
settings:
  import/parsers:
    '@typescript-eslint/parser': [".ts", ".tsx"]
  import/resolver:
    typescript:
      alwaysTryTypes: 1
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - react
  - jest
  - '@typescript-eslint'
  - import
  - prettier
rules:
  strict: 0
  no-unused-vars:
    - error
    - varsIgnorePattern: "React"
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
  import/no-default-export: error
  import/no-unresolved:
    - error
    - ignore:
      - "\\.svg$"
  jsx-a11y/anchor-is-valid: 0
  jsx-a11y/media-has-caption: 0
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx", ".ts", ".tsx", ".svg"] }]
  react/jsx-props-no-spreading: 0
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  react/prefer-stateless-function: 0
  react/react-in-jsx-scope: 2
  '@typescript-eslint/indent': 0
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: "React"
  prettier/prettier: 'error'
